version: '3.8'

services:
  login-app:
    build: 
      context: ./Authentication
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=
      - DB_PORT=
      - DB_NAME=
      - DB_USER=
      - DB_PASSWORD=
    depends_on:
      - postgres
    networks:
      - app-network

  react-app:
    build:
      context: ./E-commerce
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://backend:8080
    networks:
      - app-network

  backend:
    build:
      context: ./E-commerceBackend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: registry.hub.docker.com/library/postgres:latest
    environment:
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent volume
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:  # Define the volume
